---
- name: configures a rhel server
  hosts: all
  tasks:
    - name: Add users and SSH keys
      ansible.builtin.include_tasks:
        file: tasks/add_user.yml

    - name: Install Packages
      ansible.builtin.include_tasks:
        file: tasks/install_packages.yml

    - name: Install Docker on hosts in the docker group
      ansible.builtin.include_tasks:
        file: tasks/install_docker.yml
      when: "'rhel_docker_hosts' in group_names"

    - name: setup ssh
      ansible.builtin.include_tasks:
        file: tasks/setup_ssh.yml

  handlers:
    - name: restart sshd
      ansible.builtin.service:
        name: sshd
        state: restarted
    